# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectFile: 'template-service/template.sln'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: "Publishing"
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: $(projectFile)
    arguments: '-o "$(build.artifactstagingdirectory)\WebApp.zip" -c $(buildConfiguration) --os linux'
    modifyOutputPath: false

- task: PublishBuildArtifacts@1