version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api: 
    build: 
      dockerfile:  src/Api/Dockerfile
      context: ../
    container_name: api_container
    ports:
      - "7543:8080"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=test;Username=myusername;Password=mypassword 

  client:
    build:
      dockerfile: src/Client/Dockerfile
      context: ../
    container_name: client_container
    ports:
      - "3000:3000"
volumes:
  postgres_data: